model_name: GGCNN
log_dir: logs/plane_grasping/ggcnn
use_rgb: 1
use_depth: 0

checkpoints:
  ggcnn: plane_grasping/GGCNN/checkpoints/ggcnn_weights_cornell/ggcnn_epoch_23_cornell_statedict.pt
  ggcnn2: plane_grasping/GGCNN/checkpoints/ggcnn2_weights_cornell/epoch_50_cornell_statedict.pt